travis:
  secure:
    BINSTAR_TOKEN: AnAzM1S5sVHGw6R1SLa8CYDAE4tLUzU/kWhIeP5/TYEpnepu1u/6vSxBzzhOuBDH2ejpMVBi5RcIV0+ClYI9cnn703L9pozgjFoiDcND0HGt+bOOsAfpJyXZypA6pxTdtQS+RmFHTYyCXuUvi4NqX/sY1DxhmzPh5cZIQHsDsmDP+2Df+lOQbVKhp0QArUn1zjy/gtxnM8I36veiBB3gYvXyFG5xnTH1nFjJ4N0xAIFcVem/ZtjpASqYk5Ebmy6irTWqx41Y+JXggABHzfFO/tSnVNaApUymKUzVPiGwv7FUj5eB+vcSefxmdhc2QXj+O9EXSUKPUXrU6SCGEEnk49vC8JU6Tu3jVjyGa8XHOO7MBhJWjG6y8HAWcgzSlRZRuSCW5DRKbEDBMtiHdfn956VCkwe70m7J4FCH7/GlGPcmGifgdXVMUyVT4PAVTLBumDCmQrCC81cKLzObHXzzbiHqqLGIh5PrxzDUERBq2MeZD+R3xd4bYKu0vMY4bDDoMhbBfHow3oJY0eHllwn8UiMATW3HkliTTwj1Pd1A6MZ28bhSVUsFrY5XuB7sHh9YCNZQZk5YdqusXc8kOXpggizrdlfJyzyDI7imr6tfYaotmmjzLWQoEH8i0j/wKBWbMYMNoZwcupKZcH6u2shEL4XAVOH87CPw9eI013TA7iw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
